name: My First Workflow 

on: 
  workflow_dispatch

env:
  var1: heddala
  var2: heddala2

jobs:
    first_job:
      uses: ./.github/workflows/reusable-workflow.yml
    
    Second_job:
      concurrency: 
        group: yemo
        cancel-in-progress: true
      needs: first_job
      runs-on: ubuntu-latest
      steps:
          - name: Source Code CheckOut
            uses: actions/checkout@v4

          - name: First Step
            env:
              var2: heddala2.stepvalue
            run: echo "My First Example $var2"

          - name: Sleep Task
            run: sleep 600s
    