name: My First Workflow 

on: [push, workflow_dispatch]

env:
  var1: heddala
  var2: heddala2

jobs:
    first_job:
      uses: ./.github/workflows/reusable-workflow.yml
      secrets:
        key1: $var1
        key2: $var2
      with:
        input1: 'brvunrnvur'
    
    Second_job:
      concurrency: 
        group: yemo
        cancel-in-progress: true
      needs: first_job
      uses: ./.github/workflows/reusable-workflow.yml
      secrets:
        key1: $var1
        key2: $var2
      with:
        input1: ${{ vars.VAR1 }} 