name: My First Workflow 

on: [push, workflow_dispatch]

env:
  var1: heddala
  var2: heddala2

jobs:
    environment_vars:
      runs-on: ubuntu-latest
      steps:
        - name: Create New Env Var
          run: |
            echo "envvar1=var10" >> $GITHUB_ENV
        
        - name: Print Env
          run: 
            echo "$envvar1"

    first_job:
      uses: ./.github/workflows/reusable-workflow.yml
      secrets:
        key1: $var1
        key2: $var2
      with:
        input1: 'brvunrnvur'
    
    Second_job:
      concurrency: 
        group: yemo
        cancel-in-progress: true
      needs: first_job
      uses: ./.github/workflows/reusable-workflow.yml
      secrets:
        key1: $var1
        key2: $var2
      with:
        input1: ${{ vars.VAR1 }} 