name: My First Workflow 

on: [ push, issues]

env:
  var1: heddala
  var2: heddala2

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Source Code CheckOut
              uses: actions/checkout@v4

            - name: First Step
              run: echo "My First Example ${{ env.var1 }}"
    
    Second_job:
      needs: first_job
      runs-on: ubuntu-latest
      steps:
          - name: Source Code CheckOut
            uses: actions/checkout@v4

          - name: First Step
            env:
              var2: heddala2.stepvalue
            run: echo "My First Example $var2"
    