
on: 
    workflow_call: 
      secrets:
        key1:
          description: 'test value for key1'
          required: true
        key2:
          description: 'test value for key2'
          required: true
      inputs:
        input1:
          required: true
          type: string
      outputs:
        output1:
          description: 'outputvalue'
          value: yo_yo_job.steps.
jobs:        
    yo_yo_job:
        runs-on: ubuntu-latest
        steps:
            - name: Source Code CheckOut
              uses: actions/checkout@v4

            - name: First Step
              run: echo "My First Example ${{ env.var1 }}"
            
            - name: Use called workflow secrets
              run: echo "${{ secrets.key1 }}"

            - name: Print Inputs
              run: echo ${{ inputs.input1 }}