
on: 
    workflow_call: 

jobs:        
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Source Code CheckOut
              uses: actions/checkout@v4

            - name: First Step
              run: echo "My First Example ${{ env.var1 }}"

            - name: Use Secrets
              run: echo "${{ env.var2 }}"